---
- name: Deploy New configuration Core Switches
  hosts: core_switches
  gather_facts: false
  connection: local

  vars:
    admin:
      username: cisco
      password: cisco

  tasks:
    - name: Deploy New configuration Core Switches
      ios_config:
        provider: "{{ admin }}"
        authorize: yes
        timeout: 30
        parents:
          - interface range g0/0 - 3, g1/0 - 3, g2/0 - 3, g3/0 - 3
        lines:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport nonegotiate


- name: Deploy New configuration Access Switches S4
  hosts: s4
  gather_facts: false
  connection: local

  vars:
    admin:
      username: cisco
      password: cisco

  tasks:
    - name: Interface Configuration
      ios_config:
        provider: "{{ admin }}"
        authorize: yes
        timeout: 30
        parents:
          - interface g0/3
        lines:
          - switchport mode access
          - switchport access vlan 10

- name: Deploy New configuration Access Switches S5
  hosts: s5
  gather_facts: false
  connection: local

  vars:
    admin:
      username: cisco
      password: cisco

  tasks:
    - name: Interface Configuration
      ios_config:
        provider: "{{ admin }}"
        authorize: yes
        timeout: 30
        parents:
          - interface g0/3
        lines:
          - switchport mode access
          - switchport access vlan 20

- name: Deploy New configuration Access Switches S6
  hosts: s6
  gather_facts: false
  connection: local

  vars:
    admin:
      username: cisco
      password: cisco

  tasks:
    - name: Interface Configuration
      ios_config:
        provider: "{{ admin }}"
        authorize: yes
        timeout: 30
        parents:
          - interface g0/3
        lines:
          - switchport mode access
          - switchport access vlan 30


- name: Show Interface Information
  hosts: all_switches
  gather_facts: false
  connection: local

  vars:
    admin:
      username: cisco
      password: cisco

  tasks:
    - name: Show Interface Information
      ios_command:
        provider: "{{ admin }}"
        authorize: yes
        commands:
          - "show run | begin interface"
      register: output

    - name: Debug output
      debug: var=output.stdout_lines
